jobs:
  evaluate:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install openai

      - name: Run Tests
        run: |
          # Run your tests here
          echo "Run your tests here and save results as needed"

      - name: Grade the Project
        run: python grade_project.py
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
